### ISSUE TITLE
Zeile 69 in Wagon

### ISSUE THREAD

**Issue by SMN321** [ArneMartin1/EIDI-1#1]
sollte es nicht eher this.etage = 2; heißen? sonst änderst du ja nur die Variable innerhalb der Methode und
nicht die Objektvariable.

**Comment by ottojo** [comment]
[this](https://github.com/ArneMartin1/EIDI-1/blob/e6348e6f7ce0ae21b5c892142812e365a6802793/08-martin-arne/Wagon.java#L66-L70)

**Comment by ArneMartin1** [comment]
stimmt, dann muss es in Zeile 62 aber auch geändert werden, oder?

**Comment by SMN321** [comment]
ja, und in Zeile 56 muss ein else-statement, sonst macht die if-Abfrage davor keinen Sinn

**Comment by ArneMartin1** [comment]
jop
